### ISSUE TITLE
Title should be APNAGHAR 

### ISSUE THREAD

**Issue by aniketartani** [QAZIMAAZARSHAD/Real-Estate-Website#1]
I would like to change the title of the website from APNAGHAR.COM to APNAGHAR

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead if you want to.

But I guess you are LGM-SOC'21 participant. And this project is not part of LGM-SOC'21.

**Comment by aniketartani** [comment]
NO, I am just an open source contributer

**Comment by aniketartani** [comment]
Please assign me this issue!

**Comment by QAZIMAAZARSHAD** [comment]
@aniketartani I have an issue in one of my projects, would you like to help?
